# #################################################################
# /qompassai/volta/.gitlab-ci.yml
# Qompass AI Gitlab Ci
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2026 Qompass AI
#
# Volta is derived from Hagrid, the software behind
# keys.openpgp.org, and this material is licensed under the
# GNU Affero General Public License, version 3 only (see
# LICENSE-AGPL). Contributions authored by Qompass AI are
# dual-licensed under AGPL-3.0 or Apache-2.0 at the
# recipient's choice (see NOTICE); that choice does not
# extend to upstream-derived material, which remains
# AGPL-3.0 only.

build, test and lint:
    image: "rust:1-bullseye"
    interruptible: true
    script:
        - apt update -qy
        - apt install -qy build-essential pkg-config clang libclang-dev nettle-dev gettext zsh
        - rustup component add clippy
        - rustup component add rustfmt
        - ./make-translated-templates
        - cargo build
        - cargo clippy --tests --no-deps --workspace
        - cargo fmt --all -- --check
        - cargo test --all
