# #################################################################
# /qompassai/volta/Cargo.toml
# Qompass AI Cargo
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2026 Qompass AI
#
# Volta is derived from Hagrid, the software behind
# keys.openpgp.org, and this material is licensed under the
# GNU Affero General Public License, version 3 only (see
# LICENSE-AGPL). Contributions authored by Qompass AI are
# dual-licensed under AGPL-3.0 or Apache-2.0 at the
# recipient's choice (see NOTICE); that choice does not
# extend to upstream-derived material, which remains
# AGPL-3.0 only.

[[bin]]
name = "volta"
path = "src/main.rs"

[[bin]]
name = "volta-delete"
path = "src/delete.rs"

[build-dependencies]
vergen = "3"

[dependencies]
volta-database = { path = "database" }
chrono = "0.4.10"
anyhow = "1"
rocket = { version = "0.5.0-rc.1", features = ["json"] }
rocket_dyn_templates = { version = "0.1.0-rc.1", features = ["handlebars"] }
rocket_codegen = "0.5.0-rc.1"
sequoia-openpgp = { version = "1", default-features = false, features = [
  "crypto-nettle",
] }
multipart = "0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
time = "0.1"
tempfile = "3.0"
structopt = "0.2"
url = "1.6"
handlebars = "4"
num_cpus = "1.0"
ring = "0.17"
base64 = "0.10"
uuid = { version = "0.7", features = ["v4"] }
rocket_prometheus = "0.10.0-rc.1"
lazy_static = "1.3.0"
gettext-macros = "0.6.1"
gettext-utils = "0.1"
gettext = "0.4"
glob = "0.3"
rfc2047 = "0.1"
hyperx = "1.4"

[dependencies.lettre]
version = "0.10.0-pre"
default-features = false
features = ["builder", "file-transport", "sendmail-transport"]
git = "https://github.com/lettre/lettre"
rev = "245c600c82ee18b766e8729f005ff453a55dce34"


[dev-dependencies]
regex = "1"

[features]
default = []

[package]
name = "volta"
version = "1.1.0"
authors = ["Matt A. Porter <map@qompass.ai>"]
build = "build.rs"
default-run = "volta"
edition = "2024"
license = "AGPL-3.0-only"
rust-version = "1.89"

[profile.release]
opt-level = 3
lto = true
debug = false

[workspace]
members = ["database", "voltactl"]
