#!/usr/bin/env zsh
# #################################################################
# /qompassai/volta/make-translated-templates
# Qompass AI Make Translated Templates
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2026 Qompass AI
#
# Volta is derived from Hagrid, the software behind
# keys.openpgp.org, and this material is licensed under the
# GNU Affero General Public License, version 3 only (see
# LICENSE-AGPL). Contributions authored by Qompass AI are
# dual-licensed under AGPL-3.0 or Apache-2.0 at the
# recipient's choice (see NOTICE); that choice does not
# extend to upstream-derived material, which remains
# AGPL-3.0 only.


for i in templates-untranslated/**/*.hbs; do
	local template=${${i#templates-untranslated/}}
	local prefix_file=${i:h}/template-prefix
	local suffix_file=${i:h}/template-suffix

	echo -n "$template: "

	echo -n "en "
	local dist_path=dist/templates/$template
	cat $prefix_file $i $suffix_file >! $dist_path

	for translated in templates-translated/*/$template(N); do
		local locale=${${translated#templates-translated/}%%/*}
		local dist_path=dist/templates/localized/$locale/$template
		if [[ ! -d ${dist_path:h} ]]; then
			mkdir -p ${dist_path:h}
		fi
		echo -n "$locale "
		# echo "cat $prefix_file $translated $suffix_file >! $dist_path"
		cat $prefix_file $translated $suffix_file >! $dist_path
	done
	echo

done
