#!/usr/bin/env zsh
# #################################################################
# /qompassai/volta/make-translated-templates
# Qompass AI Make Translated Templates
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Qompass AI
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


for i in templates-untranslated/**/*.hbs; do
	local template=${${i#templates-untranslated/}}
	local prefix_file=${i:h}/template-prefix
	local suffix_file=${i:h}/template-suffix

	echo -n "$template: "

	echo -n "en "
	local dist_path=dist/templates/$template
	cat $prefix_file $i $suffix_file >! $dist_path

	for translated in templates-translated/*/$template(N); do
		local locale=${${translated#templates-translated/}%%/*}
		local dist_path=dist/templates/localized/$locale/$template
		if [[ ! -d ${dist_path:h} ]]; then
			mkdir -p ${dist_path:h}
		fi
		echo -n "$locale "
		# echo "cat $prefix_file $translated $suffix_file >! $dist_path"
		cat $prefix_file $translated $suffix_file >! $dist_path
	done
	echo

done
