# #################################################################
# /qompassai/volta/rust-toolchain.toml
# Qompass AI Rust Toolchain
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2026 Qompass AI
#
# Volta is derived from Hagrid, the software behind
# keys.openpgp.org, and this material is licensed under the
# GNU Affero General Public License, version 3 only (see
# LICENSE-AGPL). Contributions authored by Qompass AI are
# dual-licensed under AGPL-3.0 or Apache-2.0 at the
# recipient's choice (see NOTICE); that choice does not
# extend to upstream-derived material, which remains
# AGPL-3.0 only.

[toolchain]
channel = "nightly-2026-09-25"
components = ["rustfmt", "clippy"]
