[build]
target-dir = ".target"

[target.x86_64-unknown-linux-gnu]
runner = "zig"

[profile.release]
opt-level = "z"   # Optimize for size
lto = true
strip = true

# Optional: Uncomment if using musl or cross-compilation
#[target.x86_64-unknown-linux-musl]
#linker = "zig cc -target x86_64-linux-musl"
